Add documentation for Loop accelerator
pivotal/docs-tap pull request #1787
Opened 2022-10-19 15:40 UTC by eleftherias

Which other branches should this be merged with (if any)?
Only 1.4

2022-11-01 09:40 UTC, RichardJJG commented
Hi, @eleftherias , do you have an ETA for when this will be ready to merge? I ask because the longer this stays in limbo, the more difficult it will be to merge.

2022-11-01 15:29 UTC, eleftherias commented
Hey @RichardJJG, I estimate it will be ready to merge by the end of the week.

2022-11-01 15:47 UTC, RichardJJG commented
Thanks, @eleftherias, I've created a note on the [story](https://www.pivotaltracker.com/story/show/183581479) for a writer to check back on 7 November.

2022-11-02 12:00 UTC, ericbottard commented on application-accelerator/creating-accelerators/transforms/loop.hbs.md
> +Create a new directory for every module in `modules` containing the contents of the "template" directory.
```suggestion
Create a new directory for every module in `modules` (a list of strings) based on the contents of the "template" directory.
```

2022-11-02 12:01 UTC, ericbottard commented on application-accelerator/creating-accelerators/transforms/loop.hbs.md
> +Add every artifact in `artifacts` as a Spring plugin.
```suggestion
Add every artifactId in `artifacts` (a list of strings) as a Spring plugin.
```

2022-11-02 12:01 UTC, ericbottard requested changes
LGTM with the minor changes suggested

2022-11-04 17:08 UTC, merged