DRAFT (but please review): chore:[AMR-542][AMR-544] Update docs around amr app accelerator and d…
pivotal/docs-tap pull request #2928
Opened 2023-09-19 14:37 UTC by Pivotal-Jeff-Jun

…ora data models

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

2023-09-19 14:41 UTC, xtreme-debbie-chen commented on scst-store/amr/data-model-and-concepts.hbs.md
> +Each `AppAcceleratorRun` data entry has an unique `guid`. It includes information
[This arbitrary website](https://www.scribbr.com/frequently-asked-questions/an-or-a-unique/) says that it's supposed be `a unique` 🤷‍♀️

2023-09-19 14:42 UTC, Manifaust approved these changes

2023-09-19 15:05 UTC, xtreme-debbie-chen approved these changes

2023-09-19 15:11 UTC, ohlookadollar requested changes

2023-09-19 15:11 UTC, ohlookadollar commented on scst-store/amr/data-model-and-concepts.hbs.md
> +`AggregatedLeadTime` is a velocity metric that describes the median amount of time for a
should say this is in seconds

2023-09-20 18:14 UTC, ohlookadollar approved these changes

2023-09-26 20:25 UTC, Pivotal-Jeff-Jun commented
@snneji could you merge this MR, if it looks good to you?

2023-09-27 17:03 UTC, merged