appsso: add signing key size constraint
pivotal/docs-tap pull request #2943
Opened 2023-09-22 16:09 UTC by sarahwalther

- the minimum is 2048

[#185338123]

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

2023-09-25 05:52 UTC, mamachanko requested changes

2023-09-25 05:52 UTC, mamachanko commented on app-sso/how-to-guides/service-operators/configure-token-signature.hbs.md
> +   > **Note** The minimum key size for an `Authserver` is 2048
**[issue]:** Please, update the `app-sso/reference/apis/authserver` as well for `AuthServer.spec.tokenSignature.(signAndVerifyRef,extraVerifyRefs)`.

2023-09-26 17:15 UTC, YugangW commented
@mamachanko @sarahwalther Could you please let me know if this PR is ready to be merged? Thanks!

2023-09-27 05:57 UTC, mamachanko commented
@YugangW It is ready! Thanks for checking.

2023-09-27 12:19 UTC, merged