Add deprecated warning for APIx package
pivotal/docs-tap pull request #3168
Opened 2023-12-01 21:13 UTC by shrutiyer

This change is only for 1.7. I will be making a different MR for 1.8 to completely remove the package and its docs.

cc/ @csterwa @royclarkson

2023-12-01 21:21 UTC, csterwa requested changes

2023-12-01 21:21 UTC, csterwa commented on api-validation-scoring/about.hbs.md
> +> It will be removed in TAP 1.8.
Is the abbreviation "TAP" used in other parts of the documentation? I think we may want to spell it out as Tanzu Application Platform and then not reference a version that does not exist yet. Maybe say next version of Tanzu Application Platform?

2023-12-01 22:50 UTC, csterwa requested changes

2023-12-04 15:14 UTC, csterwa requested changes

2023-12-04 15:14 UTC, csterwa commented on release-notes.hbs.md
> +- The `apix` package is deprecated and will be removed in the next Tanzu Application Platform 1.8 release.
Can you remove 1.8 here @shrutiyer ?

2023-12-04 15:16 UTC, shrutiyer commented on release-notes.hbs.md
> +- The `apix` package is deprecated and will be removed in the next Tanzu Application Platform 1.8 release.
Funny timing because I committed a few mins ago and it should already be gone

2023-12-05 12:02 UTC, merged