ootb: update profile setup instructions
pivotal/docs-tap pull request #443
Opened 2021-11-05 14:12 UTC by cirocosta

as the basic default supplychain comes already installed but it still
requires `registry.server` and `registry.repository` to be set, here we
document that right at the initial values.yaml creation, adding back the
fields that describe what we mean by `SERVER-NAME` and `REPO-NAME`.

see https://gitlab.eng.vmware.com/tap/tap-packages/-/merge_requests/146
for details

Signed-off-by: Ciro S. Costa <ciroscosta@vmware.com>

2021-11-05 18:55 UTC, BarrAndrea commented
@cirocosta Please be careful on how long you have this PR in draft mode. If it's more then a few hours we will get massive merge conflicts.

2021-11-08 11:49 UTC, RichardJJG commented
@cirocosta, if you want this in the docs for the v0.3 release you need to move this out of `draft` status in the next few hours. I'm not able to merge while this is a draft.

2021-11-08 14:02 UTC, cirocosta commented
hey @RichardJJG @BarrAndrea , thanks for the ping! just waiting on a final call from @jwntrs

2021-11-08 14:16 UTC, jwntrs approved these changes

2021-11-08 15:09 UTC, merged

2021-11-08 15:10 UTC, alexbarbato requested changes
Small nit on versioning pre-release!

2021-11-08 15:10 UTC, alexbarbato commented on getting-started.md
> +tanzu package installed update tap -p tap.tanzu.vmware.com -v 0.3.0-build.6 --values-file tap-values.yml -n tap-install
can we update `0.3.0-build.6` to `0.3.0` please!

2021-11-08 15:10 UTC, alexbarbato commented on getting-started.md
> +tanzu package installed update tap -p tap.tanzu.vmware.com -v 0.3.0-build.6 --values-file tap-values.yml -n tap-install
can we update 0.3.0-build.6 to 0.3.0 please!

2021-11-08 15:10 UTC, alexbarbato commented
Oop. I'll make these changes on main now. No worries!